# Deploy API with logging fixes
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/kids-activity-api:logging-${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/kids-activity-api:logging-${SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kids-activity-api'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/kids-activity-api:logging-${SHORT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--add-cloudsql-instances'
      - 'kids-activity-tracker-2024:us-central1:kids-activity-db-dev'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest'

timeout: '1200s'