services:
  - type: web
    name: kids-activity-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: node api/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: false