apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: scraper-detailed-job
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
          - image: gcr.io/kids-activity-tracker-2024/scraper-detailed:latest
            name: scraper
            command: ["node"]
            args: ["scraper-job.js"]
            resources:
              limits:
                cpu: "2"
                memory: "2Gi"
            env:
            - name: NODE_ENV
              value: "production"
            - name: HEADLESS
              value: "true"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: DATABASE_URL
                  key: latest
          timeoutSeconds: 3600
          serviceAccountName: 205843686007-compute@developer.gserviceaccount.com