-- Add all missing columns to Activity table
ALTER TABLE "Activity" 
ADD COLUMN IF NOT EXISTS "detailUrl" TEXT,
ADD COLUMN IF NOT EXISTS "endTime" TEXT,
ADD COLUMN IF NOT EXISTS "startTime" TEXT,
ADD COLUMN IF NOT EXISTS "courseDetails" TEXT,
ADD COLUMN IF NOT EXISTS "instructor" TEXT,
ADD COLUMN IF NOT EXISTS "prerequisitesText" TEXT,
ADD COLUMN IF NOT EXISTS "hasMultipleSessions" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "sessionCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "hasPrerequisites" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "costIncludesTax" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "taxAmount" NUMERIC(10,2),
ADD COLUMN IF NOT EXISTS "registrationEndDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "registrationEndTime" TEXT,
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;