steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/website:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://kids-activity-api-205843686007.us-central1.run.app'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/website:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'website'
      - '--image=gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=3000'

images:
  - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/website:latest'

options:
  logging: CLOUD_LOGGING_ONLY
